export const PIC_REQUEST = 'PIC_REQUEST';
export const PIC_SUCCESS = 'PIC_SUCCESS';
export const PIC_FAILURE = 'PIC_FAILURE';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';